language: objective-c
osx_image: xcode9
xcode_workspace: NexMe.xcworkspace

branches:
  only:
    - developing

before_install:
  - rvm install ruby-2.2.2
  - gem install cocoapods
  - gem install xcpretty -N
  - brew update
  - brew install swiftlint || true
podfile: Podfile
script: bundle exec pod install --repo-update
